// This file emulates the file that would normally be created by Bison
// This file would normally be generated by Bison

//due to a weird compilation setup, I had to move the includes to the .h

#include "calc.tab.h"

FILE *yyin = NULL;
char *yytext = NULL;

int ExportToken(FILE *yyout, int token)
{
    fprintf(yyout, "<%03i> %s\n", token, ((yytext)? yytext:""));//nice thing is this returns the number of characters outputted.
    if (yytext)
       free(yytext);
    yytext = NULL;
    return 0;
}

int yyparse(char const *filename)
{
   FILE *yyout;
   int token;

   yyin = fopen(filename, "rt");
   if (!yyin)
   {
      printf("File %s failed to open.\n", filename);
      return -1;
   }

   yyout = fopen(OUTPUTFILE, "wt");
   if (!yyout)
   {
      printf("File %s failed to open.\n", OUTPUTFILE);
      return -2;
   }

   while (token=yylex())
      ExportToken(yyout, token);
   ExportToken(yyout, token);

   fclose(yyin);
   fclose(yyout);

   return 0;
}

